### ISSUE TITLE
App crashes when Water is pressed 

### ISSUE THREAD

**Issue by williamd1k0** [7LPdWcaW/GrowTracker-Android#266]
I started testing the app yesterday and it's always crashing when I try to press "Water".

App version: 2.6.3 (F-Droid)
Phone Specs:
Android: 7.1.2 (LineageOS 14.1)
Qualcomm Snapdragon 430 8937
Processor clock: 1.40 GHz
Number of cores: 8
GPU: Adreno 505 

### Android Logcat
```java
FATAL EXCEPTION: main
Process: me.anon.grow, PID: 10154
java.lang.RuntimeException: Unable to start activity ComponentInfo{me.anon.grow/me.anon.grow.AddWateringActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at me.anon.grow.fragment.WateringFragment.onActivityCreated(WateringFragment.java:191)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1188)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:6701)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
	... 9 more
```

**Comment by JoshuaKir** [comment]
Hi! I was having the same issue but then added a new garden, put my current plant in that garden, and the water function started working. Thanks for posting the error log, having read it was an indexing out of bounds issue I figured it was because it was trying to iterate through gardens but there were no gardens lol. Hope this helps!
