### ISSUE TITLE
[GrowTracker][V2.5.1]The application crashes when i click on backup size limit

### ISSUE THREAD

**Issue by 44asad** [7LPdWcaW/GrowTracker-Android#89]
### Expected behavior:
I expected that the application should not be crash when i click on Backup size limit option.

### Actual behavior:
After configure the application when i click on Backup Suze limit option,the application is you can see in bug vieo proprealy.

### How to reproduce:
1.Download the app from playstore and open the app.
2.Then click on team conditions accept.
3.Naw click on account manu icon and setting option.
4.Then click on backup size & type number 
5.Click- ok 
6.Note the Bug.

### information
App version:v2.5.1
os:Android 6.0.1
Device:samsung J5
### Recording of the bug

https://youtu.be/L07gNX2ykNE

### Logcat:
<pre><code>06-26 23:01:42.326 10073 10073 E AndroidRuntime: FATAL EXCEPTION: main
06-26 23:01:42.326 10073 10073 E AndroidRuntime: Process: me.anon.grow, PID: 10073
06-26 23:01:42.326 10073 10073 E AndroidRuntime: java.lang.NumberFormatException: Invalid int: "1345??"
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at java.lang.Integer.invalidInt(Integer.java:138)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at java.lang.Integer.parse(Integer.java:410)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at java.lang.Integer.parseInt(Integer.java:367)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at java.lang.Integer.parseInt(Integer.java:334)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at me.anon.lib.helper.BackupHelper.limitBackups(BackupHelper.kt:50)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at me.anon.lib.helper.BackupHelper.limitBackups$default(BackupHelper.kt:46)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at me.anon.lib.helper.BackupHelper.backupJson(BackupHelper.kt:29)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at me.anon.grow.fragment.SettingsFragment.onPreferenceClick(SettingsFragment.java:620)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.preference.Preference.performClick(Preference.java:1230)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:298)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.widget.AdapterView.performItemClick(AdapterView.java:346)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.widget.AbsListView.performItemClick(AbsListView.java:1547)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.widget.AbsListView$PerformClick.run(AbsListView.java:3826)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.widget.AbsListView$3.run(AbsListView.java:5848)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-26 23:01:42.326 10073 10073 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</code></pre>

**Comment by 44asad** [comment]
@7LPdWcaW
