### ISSUE TITLE
The application crashes when i click on Restore From Backup

### ISSUE THREAD

**Issue by 44asad** [7LPdWcaW/GrowTracker-Android#93]
### Expected behavior:
I expected that the application should not be crash when i click on Restore from Backup Option.

### Actual behavior:
After configure the application when i click on Restore from backup option,the application is you can see in bug vieo proprealy.

### How to reproduce:
1.Download the app from playstore and open the app.
2.Then click on account manu icon and setting option.
3.click on  restore backup Naw 
4.Then try to again 
6.Note the Bug.

### information
App version:v2.5.1
os:Android 6.0.1
Device:samsung J5
### Recording of the bug
https://youtu.be/vXEDy1DttLE

### Logcat:
<pre><code>06-26 23:08:17.986 11900 11900 E AndroidRuntime: FATAL EXCEPTION: main
06-26 23:08:17.986 11900 11900 E AndroidRuntime: Process: me.anon.grow, PID: 11900
06-26 23:08:17.986 11900 11900 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.text.format.DateFormat.getTimeFormatString(DateFormat.java:278)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.text.format.DateFormat.getTimeFormatString(DateFormat.java:267)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.text.format.DateFormat.getTimeFormat(DateFormat.java:257)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at me.anon.grow.fragment.SettingsFragment$1BackupData.toString(SettingsFragment.java:636)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at java.lang.StringBuilder.append(StringBuilder.java:202)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at me.anon.grow.fragment.SettingsFragment$13.onClick(SettingsFragment.java:793)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1229)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.widget.AdapterView.performItemClick(AdapterView.java:346)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.widget.AbsListView.performItemClick(AbsListView.java:1547)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.widget.AbsListView$PerformClick.run(AbsListView.java:3826)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.widget.AbsListView$3.run(AbsListView.java:5848)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-26 23:08:17.986 11900 11900 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</code></pre>

**Comment by 44asad** [comment]
@7LPdWcaW

**Comment by 44asad** [comment]
@7LPdWcaW
check its
